/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.usuario.AHTTPTest;

public final class Manifest {
    public static final class permission {
        public static final String PAYMENT_BROADCAST_PERMISSION="plugin.fortumo.PAYMENT_BROADCAST_PERMISSION";
    }
}
